// 静态资源路径
export const Resources = [
  ['background', 'images/background.jpg'],
  ['restart', 'images/start.png'],
  ['home', 'images/home.jpg'],
  ['fruit', 'images/fruit.png'],
  ['ranklist', 'images/ranklist.png'],
  ['gamedesc', 'images/gamedesc.png'],
  ['desc', 'images/desc.png'],
  ['countdown1', 'images/countdown1.png'],
  ['countdown2', 'images/countdown2.png'],
  ['countdown3', 'images/countdown3.png'],
  ['scorebg', 'images/scorebg.png'],
  ['heart', 'images/heart.png'],
  ['break', 'images/break.png'],
  ['pointbg', 'images/pointbg.png'], 
  ['newscoreshare', 'images/newscoreshare.jpg'], 
  ['scoreshare', 'images/scoreshare.jpg'], 
  ['homeshare', 'images/homeshare.jpg'], 
  ['groupshare', 'images/groupshare.jpg'], 
]